export enum EProductActions {
  GET_LIST_PRODUCT = 'GET_LIST_PRODUCT',
  GET_PRODUCT_CATEGORY = 'GET_PRODUCT_CATEGORY',
  GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL',
  GET_LIST_PRODUCT_BY_CATEGORY = 'GET_LIST_PRODUCT_BY_CATEGORY',
  GET_LIST_PRODUCT_TOMORROW = 'GET_LIST_PRODUCT_TOMORROW',
}
