export enum EClientActions {
  GET_PROFILE = 'GET_PROFILE',
  GET_LIST_USER = 'GET_LIST_USER',
  UPGRADE_USER_TO_WHOLE_SALE = 'UPGRADE_USER_TO_WHOLE_SALE',
  DOWNGRADE_USER_TO_CUSTOMER = 'DOWNGRADE_USER_TO_CUSTOMER',
}
